#' Births dataset
#'
#' Dataset containing births data from 01-01-1968 to 2024-12-31.
#'
#' @format A data frame with N rows and K variables:
#' \describe{
#'   \item{date}{Date}
#'   \item{births}{Observed value}
#' }
#'
#'
"Births"

#' Pre-processed births model
#'
#' Object obtained from a pre-processing step applied to the daily
#' French births series included in \code{Births}.
#'
#' The object is generated by:
#' \itemize{
#'   \item selecting observations between 2019-01-01 and 2024-12-31;
#'   \item defining French national calendar effects;
#'   \item constructing holiday regressors with
#'   \code{rjd3toolkit::holidays()};
#'   \item estimating a fractional airline model with calendar effects
#'   and automatic outlier detection using
#'   \code{rjd3highfreq::fractionalAirlineEstimation()}.
#' }
#'
#' The estimation includes:
#' \itemize{
#'   \item weekly and yearly seasonal periods
#'   (\code{periods = c(7, 365.2425)});
#'   \item additive outliers (\code{"ao"});
#'   \item weekly outliers (\code{"wo"});
#'   \item level shifts (\code{"ls"}).
#' }
#'
#' The object was generated with code equivalent to:
#'
#' \preformatted{
#' date_start <- as.Date("2019-01-01")
#' date_end <- as.Date("2024-12-31")
#'
#' pre_proc_births_data <- Births[
#'   Births$date >= date_start &
#'   Births$date <= date_end,
#' ]
#'
#' frenchCalendar <- rjd3toolkit::national_calendar(
#'   days = list(
#'     rjd3toolkit::fixed_day(7, 14),
#'     rjd3toolkit::fixed_day(
#'       5, 8,
#'       validity = list(start = "1982-05-08")
#'     ),
#'     rjd3toolkit::special_day("NEWYEAR"),
#'     rjd3toolkit::special_day("MAYDAY"),
#'     rjd3toolkit::special_day("EASTERMONDAY"),
#'     rjd3toolkit::special_day("ASCENSION"),
#'     rjd3toolkit::special_day("WHITMONDAY"),
#'     rjd3toolkit::special_day("ASSUMPTION"),
#'     rjd3toolkit::special_day("ALLSAINTSDAY"),
#'     rjd3toolkit::special_day("ARMISTICE"),
#'     rjd3toolkit::special_day("CHRISTMAS")
#'   )
#' )
#'
#' cal_reg <- rjd3toolkit::holidays(
#'   calendar = frenchCalendar,
#'   start = min(pre_proc_births_data$date),
#'   length = nrow(pre_proc_births_data),
#'   type = "All",
#'   nonworking = c(6, 7)
#' )
#'
#' pre_proc_births <- fractionalAirlineEstimation(
#'   y = pre_proc_births_data$births,
#'   x = cal_reg,
#'   log = FALSE,
#'   criticalValue = 6,
#'   periods = c(7, 365.2425),
#'   outliers = c("ao", "wo", "ls"),
#'   y_time = pre_proc_births_data$date
#' )
#' }
#'
#' @format An object of class
#' \code{fractionalAirlineEstimation}.
#'
#' @source Simulated from the \code{Births} dataset.
"pre_proc_births"
